CREATE TABLE student (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  roll_no VARCHAR(10) NOT NULL,
  class VARCHAR(10) NOT NULL,
  section VARCHAR(5) NOT NULL,
  performance VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
